language: node_js
sudo: false
before_script:
- wget  https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip
- unzip consul_0.6.3_linux_amd64.zip
- mkdir consul_data
- "./consul agent -server -bootstrap -data-dir=consul_data &"
- sleep 2
- git config --global user.email "ryan@ryanbreen.com"
- git config --global user.name "Ryan Breen"
script:
- npm run test
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: aWFGzSwAFGMRKqgpsTPA+wjqGsHaPGtT8R9MgXMhshXR9X9umRpE3dt51evA0zC/2AjhXkCeXhbx8PrC33R34vWXs84ssQyGfEemttVJkBNp25x6E2w/rh6PfsFuCUQV9bNhAtQI3Ufyq98pmYyR6xtHgIwMNYBA9acreJndGu8=
after_success:
- node_modules/coveralls/bin/coveralls.js < reports/lcov.info
